[tool.poetry]
name = "desmk2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
python-dotenv = "^0.15.0"
howlongtobeatpy = "^0.1.17"
flask = "^1.1.2"
python-youtube = "^0.7.0"
google-api-python-client = "^1.12.8"
google-auth-oauthlib = "^0.4.2"
replit = "^2.0.0"
bs4 = "^0.0.1"
validators = "^0.18.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
